### ISSUE TITLE
Images from bundle in picker cannot loaded because of not-lowercase string 

### ISSUE THREAD

**Issue by dzmitry-baranau** [ChadChang/CCCountrySelector#1]
Hello!
It is beautiful library, but it needs to fix some things.
Here is fix for described issue: https://github.com/dzmitry-baranau/CCCountrySelector/commit/a859ca7f24248225fe4a930e8e6ecd60e02f51ea
Also I see ways to improve this library. If you still work on this and it is interesting for you, you can contact with me.

**Comment by ChadChang** [comment]
Hi Dzmitry Baranau,
Thanks for your feedback and actually this is my first project try to open source as practice.  It's a small and simple component so that I am so excited that it found by other one and review it.  Anyway, send a pull request or another way is better?

**Comment by dzmitry-baranau** [comment]
@ChadChang I can create PR to fix issue. I will do it today/tomorrow or you can create this fix yourself. It is just .lowercaseString for icon name.

**Comment by dzmitry-baranau** [comment]
@ChadChang Thank you. It is working fine now!
