### ISSUE TITLE
Closing picker by tap outside picker view

### ISSUE THREAD

**Issue by dzmitry-baranau** [ChadChang/CCCountrySelector#4]
It is difficult to use picker when you need to pick country from the end of the list when you are on the begin of the list. 
I think the best way in this case is to close picker by tab outside picker view

**Comment by ChadChang** [comment]
Great ! thanks for your suggestion, I will improve it.

**Comment by ChadChang** [comment]
push to dev

**Comment by dzmitry-baranau** [comment]
@ChadChang I tested your changes - looks good, but not preferred behavior as for me. 
I think, it should work with next behavior:
1) User tap to button -> picker appears. 
2) User changes in picker -> the same changes in button
3) If user want to close picker, he taps outside picker, or he taps on Done button(needed to add in top of picker).

Chad, how do you think, is it the better way to close picker?
