### ISSUE TITLE
Closing picker by tap outside picker view

### ISSUE THREAD

**Issue by dzmitry-baranau** [ChadChang/CCCountrySelector#5]
@ChadChang I tested your changes from https://github.com/ChadChang/CCCountrySelector/commit/ebd6d1b894f0d1be6b951ffaac325f0670b75cb2 - looks good, but not expected behavior as for me. 
I think, it should work with next behavior:
1) User tap to button -> picker appears. 
2) User changes in picker -> the same changes in the country selector button
3) If user want to close picker, he taps outside picker, or he taps on Done button(in this case it is needed to add Done button in top of picker with ability to localize text in button).

Chad, how do you think, is it the better way to close picker?

**Comment by ChadChang** [comment]
Thank you for your advice, I'm working on it

**Comment by ChadChang** [comment]
Hi @dzmitry-baranau   
I already push to dev  , would you like to try?

**Comment by dzmitry-baranau** [comment]
@ChadChang Looks good, but I think when user cancelled selection process and try to select country again, the picker should be set in the same state as selector button(not in previous picker state)

**Comment by ChadChang** [comment]
Okay I got it ,  I will work on it

**Comment by ChadChang** [comment]
@dzmitry-baranau  please verify if it works as you think : )

**Comment by grinkevich-alex** [comment]
@ChadChang will do it asap
