### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by dzmitry-baranau** [ChadChang/CCCountrySelector#7]
I think make sense to create new version of Selector on Swift 3 (v. 2.0)

**Comment by ChadChang** [comment]
it's in my plan : )

**Comment by ChadChang** [comment]
@dzmitry-baranau   now v2.0 support swift 3.0 : )

**Comment by ChadChang** [comment]
@dzmitry-baranau   Maybe a Xcode bug cause that I can't pass pod lib lint, so I can't publish to CocoaPods.  I still try to find the solution.

**Comment by ChadChang** [comment]
@dzmitry-baranau  sorry for wrong message,  I found that actually v2.0 is on CocoaPods . It didn't show success message when I commit, but after that I can search and find v2.0
